name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Archlinux
      run: curl -L https://github.com/sickcodes/github-actions-archlinux/raw/patch-1/install.sh | sh
    - name: mkarchiso
      run: |
        sudo pacman --noconfirm -S arch-install-scripts awk dosfstools e2fsprogs erofs-utils findutils gzip libarchive libisoburn mtools openssl pacman sed squashfs-tools
        sudo mkarchiso . o=.
        mv *.iso archiso-lts.iso
    - uses: softprops/action-gh-release@v1
      with:
        files: archiso-lts.iso
