name: Build ArchISO-lts

on: [push]

jobs:
  mkarchiso:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Archlinux
      run: curl -L https://github.com/sickcodes/github-actions-archlinux/raw/patch-1/install.sh | sh
    - name: mkarchiso
      run: |
        ! [ -d /etc/pacman.d ] && sudo mkdir -p /etc/pacman.d
        sudo echo 'Server = https://mirror.premi.st/archlinux/$repo/os/$arch'>/etc/pacman.d/mirrorlist
        sudo pacman --noconfirm -Syu arch-install-scripts awk dosfstools e2fsprogs erofs-utils findutils gzip libarchive libisoburn mtools openssl pacman sed squashfs-tools
        sudo mkarchiso . o=.
        mv *.iso archiso-lts.iso
    - uses: softprops/action-gh-release@v1
      with:
        files: archiso-lts.iso
